version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    environment:
      - POSTGRESQL_USERNAME=net_keycloak
      - POSTGRESQL_PASSWORD=keycloak_password
      - POSTGRESQL_DATABASE=bitnami_keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/net/keycloak/postgresql

  keycloak:
    image: docker.io/bitnami/keycloak:23
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT_NUMBER=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=net_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak_password
      - KEYCLOAK_DATABASE_EXTERNAL=true
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_HTTPS_PORT=8081
    depends_on:
      - postgresql
    expose:
      - "8080"
      - "8081"

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
      - keycloak

volumes:
  postgresql_data:
    driver: local 